apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-news-config
  labels:
    app.kubernetes.io/name: kube-news
    app.kubernetes.io/component: app
data:
  NODE_ENV: production
  DB_HOST: kube-news-postgres
  DB_PORT: "5432"
  DB_SSL_REQUIRE: "false"
