apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-news-postgres-data
  labels:
    app.kubernetes.io/name: kube-news
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
